# Packages installed with pacstrap
BASE_PACKAGES=(
    base 
    base-devel 
    linux 
    linux-firmware 
    cryptsetup
    zram-generator
    dosfstools
    nano
    vim 
    sudo 
    networkmanager 
    nftables
    ufw
    parted 
    reflector 
    curl 
    git
    openssh
    zsh
)

# System base
SYSTEM_BASE=(
    man-pages
    man-db
    texinfo
    unzip
    zip
    wget
    rsync
    less
    tealdeer
)

# mesa
# nvidia-open
# vulkan-icd-loader
# vulkan-radeon
# vulkan-intel
# nvidia-utils


SYSTEM_AUDIO=(
    pipewire
    pipewire-audio
    pipewire-alsa
    pipewire-pulse
    wireplumber
)

# System utilities
SYSTEM_UTILS=(
  htop
  btop
  stow
  fastfetch
  fzf
  tree
  ripgrep
  bluez
  bluez-utils
  brightnessctl
  rclone
  7zip
)

# Development tools
DEV_TOOLS=(
  yazi
  neovim
  starship
  feh
)

# LSPs and compilers
LSPS=(
  python
  python-pip
  python-numpy
  pyright
  lua-language-server
)


GRAPHICAL=(
  gtk4
  gtk3
  qt6-wayland
  qt5-wayland
)


# Desktop environment
DESKTOP=(
  hyprland
  hyprpolkitagent
  xdg-desktop-portal-hyprland
  xdg-desktop-portal-gtk
  kitty
  firefox
  wl-clipboard
  wl-clip-persist
  upower
  pavucontrol
  playerctl
  libnotify
  hyprlock
  hypridle
  swww
  nwg-look # switch gtk themes
  hyprshot
  network-manager-applet
  swaync # temp
  waybar
  rofi
  nemo
  xdg-user-dirs
  waypipe
)

# Custom (still not definitive)
TEMP=(
)

# apps packages
APPS=(
  vlc
  gimp
  discord
  spotify-launcher
)

# Fonts
FONTS=(
  noto-fonts
  noto-fonts-emoji
  papirus-icon-theme
  ttf-jetbrains-mono-nerd
  ttf-noto-nerd
  inter-font
)
