# Packages installed with pacstrap
BASE_PACKAGES=(
    base 
    base-devel 
    cryptsetup
    curl 
    dosfstools
    efibootmgr
    git
    less
    linux 
    linux-firmware 
    man-db
    man-pages
    nano
    networkmanager 
    openssh
    parted 
    reflector 
    sudo 
    tealdeer
    texinfo
    ufw
    vim 
    wget
    zram-generator
    zsh
)

HARDWARE_PKGS_COMMON=(
    mesa
    vulkan-icd-loader
)

HARDWARE_PKGS_SERVER=(
    vulkan-intel
    intel-ucode
)

HARDWARE_PKGS_LAPTOP=(
    amd-ucode
    nvidia-open
    vulkan-radeon
    nvidia-utils
    acpi
    bluez
    bluez-utils
    bluetui
    brightnessctl
    tlp
)
