DEFAULT_PKGS=(
    yazi
    neovim
    lua-language-server # neovim
    starship
    htop
    btop
    fastfetch
    fzf
    rclone
    ripgrep
    rsync
    stow
    zip
    unzip
    tree
    kitty   # ssh comp
    wl-clipboard
    wl-clip-persist
    xdg-user-dirs
    xdg-utils
    waypipe
    tailscale
    syncthing
    weston
)

# LSPs and compilers
LSPS=(
  python
  python-pip
  python-numpy
  pyright
)


GRAPHICAL=(
  gtk4
  gtk3
  qt6-wayland
  qt5-wayland
)


# Desktop environment
DESKTOP=(
  hyprland
  hyprpolkitagent
  xdg-desktop-portal-hyprland
  quickshell
  firefox
  upower
  pavucontrol
  playerctl
  libnotify
  hyprlock
  hypridle
  awww
  nwg-look # switch gtk themes
  hyprshot
  network-manager-applet
  swaync # temp
  waybar
  rofi
  nemo
  feh
)

# Custom (still not definitive)
TEMP_PKGS=(
    rtkit
)

# apps packages
APPS=(
  vlc
  gimp
  discord
  spotify-launcher
)

# Fonts
FONTS=(
    ttf-jetbrains-mono-nerd
    ttf-noto-nerd
    noto-fonts
    noto-fonts-emoji
    noto-fonts-cjk
    material-symbols-font
)

SYSTEM_AUDIO=(
    pipewire
    pipewire-audio
    pipewire-alsa
    pipewire-pulse
    wireplumber
)
